version: 2
registries:
  rubygems-server-enterprise-contribsys-com:
    type: rubygems-server
    url: https://enterprise.contribsys.com
    username: "${{secrets.RUBYGEMS_SERVER_ENTERPRISE_CONTRIBSYS_COM_USERNAME}}"
    password: "${{secrets.RUBYGEMS_SERVER_ENTERPRISE_CONTRIBSYS_COM_PASSWORD}}"

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nanoc
    versions:
    - 4.11.23
  registries:
  - rubygems-server-enterprise-contribsys-com
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@tailwindcss/postcss7-compat"
    versions:
    - 2.0.4
    - 2.1.0
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: tailwindcss
    versions:
    - 1.9.6
  - dependency-name: postcss-modules
    versions:
    - 3.2.2
  - dependency-name: autoprefixer
    versions:
    - 9.8.6
  - dependency-name: elliptic
    versions:
    - 6.5.3
